pr: none
trigger:
  batch: false
  branches:
    exclude: [ '*' ]
  tags:
    include: [ '*' ]

jobs:
- job: publish
  displayName: Publish
  pool:
    name: 'Hosted Ubuntu 1604'
  steps:
  - script: |
      echo "##vso[task.setvariable variable=version]$(git tag --points-at HEAD)"
  - template: templates/publish.yml
    parameters:
      version: $(version)
      ${{ if not(endsWith(variables['version'], '.RELEASE')) }}:
        repoId: libs-milestone-local
      # TODO support release publishing
